name: docs
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
env:
  nim-version: 'stable'
  nim-src: src/${{ github.event.repository.name }}.nim
  deploy-dir: .gh-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
      - run: nimble install -Y
      - run: nim doc --index:on --project --out:${{ env.deploy-dir }} ${{ env.nim-src }}
      
      - name: "Rename to index.html"
        run: mv ${{ env.deploy-dir }}/${{ github.event.repository.name }}.html ${{ env.deploy-dir }}/index.html 
      
      - name: "Find and replace (index.html)"
        run: sed -i 's/${{ github.event.repository.name }}.html/index.html/g' ${{ env.deploy-dir }}/index.html
      
      - name: "Find and replace (idx)"
        run: sed -i 's/${{ github.event.repository.name }}.html/index.html/g' ${{ env.deploy-dir }}/${{ github.event.repository.name }}.idx
        
      - name: "Find and replace (theindex.html)"
        run: sed -i 's/${{ github.event.repository.name }}.html/index.html/g' ${{ env.deploy-dir }}/theindex.html
        
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: openpeep/openpeep.github.io
          publish_dir: ${{ env.deploy-dir }}
          destination_dir: ./find
          publish_branch: main
          enable_jekyll: true