name: docs
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
env:
  nim-version: 'stable'
  nim-src: src/find.nim
  deploy-dir: .gh-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
      - run: nimble install -Y
      - run: nimble doc --index:on --project --out:${{ env.deploy-dir }} ${{ env.nim-src }}
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: openpeep/openpeep.github.io
          publish_dir: ${{ env.deploy-dir }}
          destination_dir: ./find
          publish_branch: main
          enable_jekyll: true